image: docker:latest

# use docker-in-docker for this
services:
  - docker:dind

# pipeline image name: PROJECT_NAME.PIPELINE_ID, ex. `coin3d.456`
variables:
  PIPELINE_IMAGE_NAME: coin3d.$CI_PIPELINE_ID

# login to the registry before we do anything!
# build process might require another image
before_script: 
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - build
  - deploy
  - clean

build:
  stage: build
  script:
  - docker build -t $PIPELINE_IMAGE_NAME .

deploy:
  stage: deploy
  script:
  - docker tag $PIPELINE_IMAGE_NAME $CI_REGISTRY_IMAGE
  - docker push $CI_REGISTRY_IMAGE
  - docker rmi $CI_REGISTRY_IMAGE
  only:
  - master

clean:
  stage: clean
  script:
  - docker rmi $PIPELINE_IMAGE_NAME
